"""Create printable grid pages from card images.

Assumes source images are card-like assets (for example 2.5in x 3.5in images
generated by Reference_Cards.py and Rules_Card.py).

Examples:
  python Print_Card_Grid.py --input . --output printable_cards.pdf
  python Print_Card_Grid.py --input ./Cards --output printable_cards.png
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import List, Sequence, Tuple

from PIL import Image, ImageOps


SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description="Create printable grid pages from card images.")
	parser.add_argument("--input", type=Path, required=True, help="Folder containing card images.")
	parser.add_argument(
		"--output",
		type=Path,
		default=Path("printable_cards.pdf"),
		help="Output file. Use .pdf for multipage PDF or an image extension for PNG/JPG pages.",
	)
	parser.add_argument("--dpi", type=int, default=300, help="Output DPI (default: 300).")
	parser.add_argument(
		"--page-size",
		choices=["letter", "a4"],
		default="letter",
		help="Page size (default: letter).",
	)
	parser.add_argument(
		"--margin-in",
		type=float,
		default=0.25,
		help="Outer page margin in inches (default: 0.25).",
	)
	parser.add_argument(
		"--gap-in",
		type=float,
		default=0.0,
		help="Gap between cards in inches (default: 0.00).",
	)
	return parser.parse_args()


def page_size_px(page_size: str, dpi: int) -> Tuple[int, int]:
	if page_size == "letter":
		w_in, h_in = 8.5, 11.0
	elif page_size == "a4":
		w_in, h_in = 8.27, 11.69
	else:
		raise ValueError(f"Unsupported page size: {page_size}")
	return int(round(w_in * dpi)), int(round(h_in * dpi))


def discover_images(folder: Path, output_path: Path) -> List[Path]:
	if not folder.exists() or not folder.is_dir():
		raise FileNotFoundError(f"Input folder does not exist or is not a directory: {folder}")

	output_name = output_path.name.lower()
	output_stem = output_path.stem.lower()

	paths: List[Path] = []
	for p in folder.iterdir():
		if not p.is_file() or p.suffix.lower() not in SUPPORTED_EXTENSIONS:
			continue

		name_lower = p.name.lower()
		stem_lower = p.stem.lower()

		# Skip files that are the combined output itself or previously generated numbered pages.
		if name_lower == output_name:
			continue
		if stem_lower == output_stem or stem_lower.startswith(f"{output_stem}_"):
			continue

		paths.append(p)

	paths.sort(key=lambda p: p.name.lower())
	if not paths:
		raise FileNotFoundError(f"No supported image files found in: {folder}")
	return paths


def fit_count(page_w: int, page_h: int, card_w: int, card_h: int, margin: int, gap: int) -> Tuple[int, int, int]:
	usable_w = page_w - 2 * margin
	usable_h = page_h - 2 * margin
	cols = max(1, (usable_w + gap) // (card_w + gap))
	rows = max(1, (usable_h + gap) // (card_h + gap))
	return cols, rows, cols * rows


def choose_orientation(page_w: int, page_h: int, card_w: int, card_h: int, margin: int, gap: int) -> Tuple[int, int, int, int]:
	cols_p, rows_p, count_p = fit_count(page_w, page_h, card_w, card_h, margin, gap)
	cols_l, rows_l, count_l = fit_count(page_h, page_w, card_w, card_h, margin, gap)

	if count_l > count_p:
		return page_h, page_w, cols_l, rows_l
	return page_w, page_h, cols_p, rows_p


def load_card_images(paths: Sequence[Path]) -> List[Image.Image]:
	images: List[Image.Image] = []
	for path in paths:
		img = Image.open(path).convert("RGB")
		images.append(img)
	return images


def make_pages(
	images: Sequence[Image.Image],
	page_w: int,
	page_h: int,
	cols: int,
	rows: int,
	margin: int,
	gap: int,
	card_w: int,
	card_h: int,
) -> List[Image.Image]:
	pages: List[Image.Image] = []
	per_page = cols * rows

	grid_w = cols * card_w + (cols - 1) * gap
	grid_h = rows * card_h + (rows - 1) * gap
	start_x = (page_w - grid_w) // 2
	start_y = (page_h - grid_h) // 2

	for start in range(0, len(images), per_page):
		page = Image.new("RGB", (page_w, page_h), color=(255, 255, 255))
		batch = images[start : start + per_page]
		for i, img in enumerate(batch):
			row = i // cols
			col = i % cols
			x = start_x + col * (card_w + gap)
			y = start_y + row * (card_h + gap)

			# Ensure each source image fills a card-sized slot while preserving aspect ratio.
			placed = ImageOps.contain(img, (card_w, card_h), method=Image.Resampling.LANCZOS)
			ox = x + (card_w - placed.width) // 2
			oy = y + (card_h - placed.height) // 2
			page.paste(placed, (ox, oy))

		pages.append(page)

	return pages


def save_pages(pages: Sequence[Image.Image], output: Path, dpi: int) -> None:
	output.parent.mkdir(parents=True, exist_ok=True)
	ext = output.suffix.lower()

	if ext == ".pdf":
		first, *rest = pages
		first.save(output, save_all=True, append_images=rest, resolution=dpi)
		return

	if ext not in SUPPORTED_EXTENSIONS:
		raise ValueError("Output must be .pdf or a supported image extension (.png/.jpg/etc.)")

	stem = output.stem
	suffix = output.suffix
	for i, page in enumerate(pages, start=1):
		page_out = output.with_name(f"{stem}_{i:02d}{suffix}")
		page.save(page_out, dpi=(dpi, dpi))


def main() -> None:
	args = parse_args()
	input_folder: Path = args.input
	output_path: Path = args.output
	dpi: int = args.dpi

	margin_px = int(round(args.margin_in * dpi))
	gap_px = int(round(args.gap_in * dpi))

	image_paths = discover_images(input_folder, output_path)
	images = load_card_images(image_paths)

	# Use the first image as target slot size (all generated cards should match).
	card_w, card_h = images[0].size
	page_w, page_h = page_size_px(args.page_size, dpi)
	page_w, page_h, cols, rows = choose_orientation(page_w, page_h, card_w, card_h, margin_px, gap_px)

	if cols <= 0 or rows <= 0:
		raise RuntimeError("Card images do not fit on the selected page with current margin/gap settings.")

	pages = make_pages(
		images=images,
		page_w=page_w,
		page_h=page_h,
		cols=cols,
		rows=rows,
		margin=margin_px,
		gap=gap_px,
		card_w=card_w,
		card_h=card_h,
	)

	save_pages(pages, output_path, dpi)

	orientation = "landscape" if page_w > page_h else "portrait"
	print(f"Found {len(images)} images.")
	print(f"Page: {args.page_size} ({orientation}), {page_w}x{page_h} px @ {dpi} DPI")
	print(f"Grid: {cols} x {rows} ({cols * rows} cards/page)")
	print(f"Created {len(pages)} page(s) at {output_path}")


if __name__ == "__main__":
	main()